// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NaturalDisasterDatabaseWebsite.Models;

namespace NaturalDisasterDatabaseWebsite.Migrations
{
    [DbContext(typeof(NaturalDisasterDatabaseWebsiteContext))]
    [Migration("20200319084619_InititalCreate03")]
    partial class InititalCreate03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NaturalDisasterDatabaseWebsite.Models.Forum_msgViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comment");

                    b.Property<DateTime>("comment_time");

                    b.Property<int>("essayID");

                    b.Property<int>("userID");

                    b.HasKey("ID");

                    b.HasIndex("essayID");

                    b.HasIndex("userID");

                    b.ToTable("forum_msg");
                });

            modelBuilder.Entity("NaturalDisasterDatabaseWebsite.Models.Science_essayViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("author");

                    b.Property<DateTime>("fb_time");

                    b.Property<string>("source");

                    b.Property<string>("state");

                    b.Property<string>("title");

                    b.Property<int>("userID");

                    b.Property<string>("wz_content");

                    b.Property<string>("wz_style");

                    b.HasKey("ID");

                    b.HasIndex("userID");

                    b.ToTable("science_essay");
                });

            modelBuilder.Entity("NaturalDisasterDatabaseWebsite.Models.UsersViewModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("email");

                    b.Property<string>("head_icon");

                    b.Property<string>("occupation");

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<string>("sex")
                        .IsRequired();

                    b.Property<string>("status")
                        .IsRequired();

                    b.Property<string>("telephone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("workplace");

                    b.HasKey("ID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NaturalDisasterDatabaseWebsite.Models.Forum_msgViewModel", b =>
                {
                    b.HasOne("NaturalDisasterDatabaseWebsite.Models.Science_essayViewModel", "essay")
                        .WithMany("forum_msgs")
                        .HasForeignKey("essayID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NaturalDisasterDatabaseWebsite.Models.UsersViewModel", "user")
                        .WithMany("forum_msgs")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NaturalDisasterDatabaseWebsite.Models.Science_essayViewModel", b =>
                {
                    b.HasOne("NaturalDisasterDatabaseWebsite.Models.UsersViewModel", "user")
                        .WithMany("essay")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
